#pragma once

#include <avr/io.h>

/* HEAD LIGHT */
#define HEAD_BUTTON_PORT &PORTB
#define HEAD_BUTTON_DDR &DDRB
#define HEAD_BUTTON_PIN &PINB
#define HEAD_BUTTON_BIT 1

#define HEAD_LEDS_DDR &DDRC
#define HEAD_LEDS_PORT &PORTC
// #define HEAD_LEDS_PIN

/* TAIL LIGHT */
#define ENABLE_FADING_BRAKE_LIGHTS

#define TAIL_BUTTON_PORT &PORTD  
#define TAIL_BUTTON_DDR &DDRD
#define TAIL_BUTTON_PIN &PIND
#define TAIL_BUTTON_BIT 7

/* LIGHTS STARTUP SEQUENCE */
#define STARTUP_STEP_TIME_MS 200
#define STARTUP_TOTAL_CYCLES 5

/* ACCELEROMETER */
#define BRAKE_THRESHOLD_MG       150
#define STATIONARY_THRESHOLD_MG   40

// #define ACCELEROMETER_SCL_DDR
// #define ACCELEROMETER_SCL_PIN   
// #define ACCELEROMETER_SDA_DDR
// #define ACCELEROMETER_SDA_PIN