#pragma once

#include <avr/io.h>

/* HEAD LIGHT */
#define HEAD_BUTTON_PORT PORTB
#define HEAD_BUTTON_DDR DDRB
#define HEAD_BUTTON_PIN PINB
#define HEAD_BUTTON_BIT 1

#define HEAD_LEDS_DDR DDRC
#define HEAD_LEDS_PORT PORTC
// #define HEAD_LEDS_PIN

/* TAIL LIGHT */
#define TAIL_BUTTON_PORT PORTD  
#define TAIL_BUTTON_DDR DDRD
#define TAIL_BUTTON_PIN PIND
#define TAIL_BUTTON_BIT 7

#define TAIL_LEDS_PORT 
#define TAIL_LEDS_DDR
// #define TAIL_LEDS_PIN  // not relevant anymore 

#define STARTUP_SEQUENCE_INTERVAL_MS 200
#define STARTUP_SEQUENCE_CYCLES 5

/* ACCELEROMETER */
// #define ACCELEROMETER_SCL_DDR
// #define ACCELEROMETER_SCL_PIN   
// #define ACCELEROMETER_SDA_DDR
// #define ACCELEROMETER_SDA_PIN