; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src
include_dir = inc

[env:esp32dev]
platform = espressif32  # edijf;slahfslvlsk
board = esp32dev
framework = arduino

monitor_speed=115200

lib_deps = 
    solidgeek/VescUart @ ^1.0.1             # VESC data over UART
    joba-1/Joba_JbdBms @ ^2.1               # BMS data over UART  
    h2zero/NimBLE-Arduino@ 1.4.1           # BLE for ESP32
    adafruit/Adafruit SSD1306 @ ^2.5.15     # OLED Display

build_flags =
    -I inc