; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano_dev]
platform = atmelavr
board = nanoatmega328
framework = ; bare-metal
upload_protocol = arduino
upload_speed = 115200
monitor_speed = 9600
; External 16 MHz clock
board_build.f_cpu = 16000000L
; build_flags = -DF_CPU=16000000UL  ; Redundant cuz of above?

[env:raw_dev]
platform = atmelavr
board = atmega328p
framework = ; bare-metal
; upload_protocol = arduinoisp
upload_protocol = custom
upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    m328p
    -c
    arduino
    -P
    COM5
    -b
    19200
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

; upload_port = COM5 ; CHANGE AS NEEDED depending on port of Arduino programmer
upload_speed = 19200 ; ArduinoISP default baud rate
; Tell compiler to assume CPU clock of 8 MHz
board_build.f_cpu = 8000000L
; build_flags = -DF_CPU=8000000UL  ; Redundant cuz of above?
; Define fuses (burn with `pio run -e raw_dev -t fuses`)
board_fuses.lfuse = 0b11100010 ; Run on internal 8 MHz RC (no division by 8 to result in 1 MHz)
board_fuses.hfuse = 0b11011011 ; Enable ISP programming. Start from main (not bootloader).
board_fuses.efuse = 0b11111101 ; Reset if VCC below 2.7 V